version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t docker:flasktut .
      - docker tag docker:flasktut $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/docker:flasktut     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/docker:flasktut
